name: Integration tests
env:
  release_major: 9

on: [push, pull_request]

jobs:
  build_llvm:
    name: check-all lld
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
    - name: Determine friendly label for this branch
      id: nicer-github-ref
      uses: johnwbyrd/nicer-github-ref@master
      with:
        ref: ${{ github.ref }}
    - name: Set install directory
      id: workspacedir
      uses: johnwbyrd/setenvdir@master
      with:
        path: ${{ github.workspace }}
    - name: On Windows, persist Visual Studio environment variables as Github environment variables
      if: startsWith(matrix.os, 'windows')
      uses: llvm/actions/setup-windows@master
      with:
        arch: amd64
    - name: Install gnuwin32 and zip on Windows
      if: startsWith(matrix.os, 'windows')
      run: choco install gnuwin32-coreutils.install zip
    - name: Install Ninja
      uses: llvm/actions/install-ninja@master
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Test LLVM
      uses: llvm/actions/build-test-llvm-project@master
      with:
        cmake_args: -G Ninja -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="MOS" -DLLVM_ENABLE_PROJECTS="clang;lld;" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ steps.workspacedir.outputs.path }}/install
    - name: Create distribution
      run: |
        cd build
        ninja install 
    - name: Zip distribution
      run: |
        cd install
        zip -9 -r ../llvm-${{ steps.nicer-github-ref.outputs.ref }}-${{ matrix.os }}.zip .
    - name: Update release
      uses: johnwbyrd/update-release@master
      id: update-release
      with:
        token: ${{ secrets.LLVM_MOS_UPDATE_RELEASE_TOKEN }}
        files: llvm-${{ steps.nicer-github-ref.outputs.ref }}-${{ matrix.os }}.zip
